# =============================================================================
# GOOGLE CLOUD BUILD - LIMS LABORATORIO
# =============================================================================
# Optimizado para costos mínimos:
# - Máquina E2_MEDIUM (en lugar de E2_HIGHCPU_8) = -70% costo
# - Cloud Run (en lugar de App Engine) = pay-per-use, scale-to-zero
# - Disco 30GB (en lugar de 100GB) = -70% storage
# - Logs estructurados = más eficiente
# =============================================================================

steps:
  # -------------------------------------------------------------------------
  # PASO 1: BUILD DE IMAGEN DOCKER
  # -------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "📦 CONSTRUYENDO IMAGEN DOCKER"
        echo "=========================================="
        echo "Branch: ${BRANCH_NAME}"
        echo "Commit: ${SHORT_SHA}"
        echo "Timestamp: $(date)"
        echo ""

        # Build con cache de capas
        docker build \
          --cache-from gcr.io/${PROJECT_ID}/lims-app:latest \
          -t gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/lims-app:latest \
          .

        echo ""
        echo "✅ Imagen construida:"
        docker images gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA}
    timeout: '900s'

  # -------------------------------------------------------------------------
  # PASO 2: PUSH A ARTIFACT REGISTRY
  # -------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    waitFor: ['build']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "📤 SUBIENDO IMAGEN A CONTAINER REGISTRY"
        echo "=========================================="

        docker push gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA}
        docker push gcr.io/${PROJECT_ID}/lims-app:latest

        echo ""
        echo "✅ Imagen subida: gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA}"
    timeout: '300s'

  # -------------------------------------------------------------------------
  # PASO 3: DEPLOY A CLOUD RUN (SERVERLESS - PAY PER USE)
  # -------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    waitFor: ['push']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "🚀 DESPLEGANDO A CLOUD RUN"
        echo "=========================================="

        # Deploy a Cloud Run con configuración optimizada para costos
        gcloud run deploy lims-app \
          --image gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA} \
          --platform managed \
          --region ${_REGION} \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5 \
          --timeout 300 \
          --concurrency 80 \
          --port 8080 \
          --allow-unauthenticated \
          --set-env-vars "NODE_ENV=production,NEXTAUTH_URL=${_APP_URL}" \
          --quiet

        # Obtener URL del servicio
        SERVICE_URL=$(gcloud run services describe lims-app \
          --platform managed \
          --region ${_REGION} \
          --format 'value(status.url)')

        echo ""
        echo "=========================================="
        echo "✅ DESPLIEGUE COMPLETADO"
        echo "=========================================="
        echo "🌐 URL: $SERVICE_URL"
        echo "📦 Imagen: gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA}"
        echo "📍 Región: ${_REGION}"
        echo ""

        # Health check
        echo "🔍 Verificando health check..."
        sleep 5
        curl -sf "$SERVICE_URL/api/health" && echo "✅ Health check OK" || echo "⚠️ Health check pendiente"
    timeout: '600s'

# -------------------------------------------------------------------------
# CONFIGURACIÓN GLOBAL
# -------------------------------------------------------------------------
timeout: '1800s'

# Logs más eficientes
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
  diskSizeGb: 30
  substitutionOption: 'ALLOW_LOOSE'
  dynamicSubstitutions: true

# Variables de sustitución
substitutions:
  _REGION: 'us-central1'
  _APP_URL: 'https://lims-app-HASH.run.app'

# Imágenes que se guardan en el registro
images:
  - 'gcr.io/${PROJECT_ID}/lims-app:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/lims-app:latest'
